
(define (fibonacci n)
    (if (<= n 1)
            n
            (+ (fibonacci (- n 1)) (fibonacci (- n 2)))))

(define (main)
(display (fibonacci 0))
(newline)
(display (fibonacci 1))
(newline)
(display (fibonacci 2))
(newline)
(display (fibonacci 3))
(newline)
(display (fibonacci 4))
(newline)
(display (fibonacci 5))
(newline)
(display (fibonacci 6))
(newline)
(display (fibonacci 7))
(newline)
(display (fibonacci 8))
(newline)
(display (fibonacci 9))
(newline)
(display (fibonacci 10))

) 