(define (multipleExpressionTest)
    (display "Starting the expression test...")
    (newline)
    (display "1 + 2 = ")
    (display (+ 1 2))
    (newline)
    (display "3 * 4 = ")
    (display (* 3 4))
    (newline)
    (display "5 - 3 = ")
    (display (- 5 3))
    (newline)
    (display "6 / 2 = ")
    (display (/ 6 2))
    (newline)
    #t
)

(define (multipleExpressionTest2)
    (* 3 2)
    (+ 3 2)
    (- 3 2)
    "text"
)

(define (main)
    (display (multipleExpressionTest))
    (newline)
    (display (multipleExpressionTest2))
    (newline)
    (display (let ((a 10)
            (b 20)
            (c 30))
        (display a)
        (display " + ")
        (display b)
        (display " = ")
        (display (+ a b))
        (newline)
        (display "b * c = ")
        (display (* b c))
        (newline)
        (+ a b c)
        )
    )
)
