(define (sumar-dos-valors)
  (let ((val1 (read))
        (val2 (read)))
     (display (+ val1 val2))
     )
)

(define (main)
    (display (read))
    (newline)
    (display (read)) 
    (newline)
    (display (read)) 
    (newline)
    (display (read)) 
    (newline)
    (display (read)) 
    (newline)
    (display (read)) 
    (newline)
    (display (read)) 
    (newline)
    (display (read))
    (newline)
    (display (read))
    (newline)
    (display (read))
    (newline)
    (display (read))
    (newline)
    (sumar-dos-valors)
)